/**
 * © Copyright HCL Technologies Ltd. 2019. 
 * LICENSE: Apache License, Version 2.0 https://www.apache.org/licenses/LICENSE-2.0
 */
package com.hcl.appscan.issuegateway.applications;

import java.util.ArrayList;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;

import com.fasterxml.jackson.databind.ObjectMapper;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;

@RestController
@Api(tags="applications")
@RequestMapping("/applications")
public class GetApplicationsController {
	private final Logger logger =LoggerFactory.getLogger(this.getClass());
	List<String> errors = new ArrayList<String>();
	
	@RequestMapping(method=RequestMethod.GET, produces="application/json")
	@ApiOperation(value="Get the list of Applications",notes="This API will give the list of applications associated with the account.Account details need to be provided by the user in form of id and secret."
    		+ "Id and secret can be generated by using the ASE API POST /keylogin/apikeylogin or in case of ASoC, it can be genreated from the cloud account. "
    		+ "For simplicity the response contains only name and id of the application. ")
	ResponseEntity<String> getResult(GetApplicationData applicationData) throws Exception {
		try {
    		logger.debug("New Request.  Payload:\n" + new ObjectMapper().writerWithDefaultPrettyPrinter().writeValueAsString(applicationData));
    	} 
		catch (Exception e) 
		{
			logger.error("Error parsing JSON", e);
		}
		ApplicationsRetrievalHandler obj=new ApplicationsRetrievalHandler();
		return obj.retrieveApplicationList(applicationData, errors);
	}
}

